### PR TITLE
Added docs requirements file and better .gitignore

### PR DESCRIPTION
**Pull request by philipstarkey**
The docs requirements file now ensures PyQt5 is installed when building docs on readthedocs, which is necessary for sphinx autodoc to work correctly.

I've also updated the .gitignore file. This is mostly based on the generic GitHub Python .gitignore (that you can create when making a new repository) with a few extras at the end for our own rules

### CODE REVIEW

**Comment by chrisjbillington** [comment]
Annoying that github doesn't show the images in the images tab, but apparently I can just drag and drop every png into this comment so here we go:

lyse_16x16
lyse_22x22
lyse_32x32
lyse_64x64
lyse_128x128
lyse_256x256

--------

blacs_16x16
blacs_22x22
blacs_32x32
blacs_64x64
blacs_128x128
blacs_256x256

--------

labscript_16x16 png
labscript_22x22
labscript_32x32
labscript_64x64
labscript_128x128
labscript_256x256

--------

runviewer_16x16
runviewer_22x22
runviewer_32x32
runviewer_64x64
runviewer_128x128
runviewer_256x256

--------

runmanager_16x16
runmanager_22x22
runmanager_32x32
runmanager_64x64
runmanager_128x128
runmanager_256x256

--------

labscript-banner_32
labscript-banner_64
labscript-banner_128
labscript-banner_256

--------

labscript-suite-square-dark_138
labscript-suite-square-dark_276
labscript-suite-square-dark_552

--------

labscript-suite-square-white_138
labscript-suite-square-white_276
labscript-suite-square-white_552

--------

labscript-suite-rectangular-white_70
labscript-suite-rectangular-white_140
labscript-suite-rectangular-white_280

--------

labscript-suite-rectangular-transparant_70
labscript-suite-rectangular-transparant_140
labscript-suite-rectangular-transparant_280

**Comment by chrisjbillington** [comment]
Sweet, looks good to me

**Comment by rpanderson** [comment]
> I've also updated the .gitignore file. This is mostly based on the generic GitHub Python .gitignore (that you can create when making a new repository) with a few extras at the end for our own rules

There's a variant of this that got added in labscript-suite/labscript-suite#37. Notable differences are:

Present in labscript-suite's .gitignore but not here:
```
# Distribution / packaging
pip-wheel-metadata/
share/python-wheels/

# Unit test / coverage reports
.nox/
*.py,cover

# Django stuff:
db.sqlite3-journal

# Sphinx documentation
docs/html/

# IPython
profile_default/
ipython_config.py

# PEP 582; used by e.g. github.com/David-OConnor/pyflow
__pypackages__/

# Celery stuff
celerybeat.pid

# mypy
.dmypy.json
dmypy.json

# Pyre type checker
.pyre/

# Editors
.vscode/
```

Present in this .gitignore but not labscript-suite
```
# Sphinx documentation
docs/_build/

# conda build results
conda_build
conda_packages

# LaTeX build results
*.out
*.log
*.aux
*.toc
```

The only ones of consequence to us are likely those we've added. For me that was changing `docs/_build/` to `docs/html/` as this is the location we're building html documentation currently for the labscript-suite metapackage, and obviously the conda ones.

**Comment by philipstarkey** [comment]
Ah, I based this on the .gitignore I had on one of my other projects but I may have deleted some lines...we should probably try and keep it consistent (and personally I would start from the GitHub Python default as the base)

**Comment by rpanderson** [comment]
Yep, this is the GitHub Python default as of a few weeks ago with only the following lines added/changed:
```
# Sphinx documentation
docs/html/

# Editors
.vscode/
```

**Pull request merged**
