### PR TITLE
Introduce a new attribute for `IntermediateDevice` defining the minimum clock high time

### LINKED ISSUE #51: Recent GatedClocks-bugfix merge breaks (at least) Novatech DDS9m timing
**Original report ([archived issue](https://labscript-suite.github.io/labscript-suite-bitbucket-archive/#!/labscript_suite/labscript/issues/51)) by Lincoln Turner (Bitbucket: [lincolndturner](https://bitbucket.org/%7B7e35ca32-09d7-4a25-a548-32edef727dda%7D/), GitHub: [lincolnturner](https://github.com/lincolnturner)).**

----------------------------------------
Marked as critical because it’s in mainline and a timing issue in hardware many of us use.

I initially reported this as [labscript\_devices issue #35](https://bitbucket-archive.labscriptsuite.org/#!/labscript_suite/labscript_devices/issues/35/novatech-dds9m-digital-gate-being) (labscript-suite/labscript_devices#35) thinking it was Novatech DDS9m specific…

…

So I reverted to `f4405d8a8ad5aedacf37ae2dc282d529a0b9b21f`, removing the GatedClocks-bugfix merge.

Then all is well!

Shots compile. And better, they run and produce nice fluoroscence images!

And indeed @Philip Starkey 's commit `56184458fbfdf04e5f3da6c9e19267c4e1d796b4` does seem to edit code in and around this error message…

See closed issue linked above for details…

### LINKED ISSUE #85: Incorrect comparison of time intervals between clocklines for error checking
There are several issue reports (#53 and #51) that seem to relate to the same thing, which result from from a commit that I will touch on below.  I will describe our issue here before describing the fix.

Emine and I were debugging an issue in the lab where we were pretriggering a novatech to get its update to occur at a desired time.  This fails when _any_ device on the same pulseblaster is clocked before the required 110 us delay between novatech updates, even if the are on different pseudoclock lines.  

Here is the relevant code:

```            
            # Check that no two instructions are too close together:

            for i, t in enumerate(change_time_list[:-1]):
                dt = change_time_list[i+1] - t
                if dt < 1.0/clock_line.clock_limit:
                    raise LabscriptError('Commands have been issued to devices attached to clockline %s at t= %s s and %s s. '%(clock_line.name, str(t),str(change_time_list[i+1])) +
                                         'One or more connected devices on ClockLine %s cannot support update delays shorter than %s sec.'%(clock_line.name, str(1.0/clock_line.clock_limit)))
                                
                all_change_times_len = len(all_change_times)
                # increment j until we reach the current time
                while all_change_times[j] < t and j < all_change_times_len-1:
                    j += 1
                # j should now index all_change_times at "t"
                # Check that the next all change_time is not too close (and thus would force this clock tick to be faster than the clock_limit)
                dt = all_change_times[j+1] - t
                if dt < 1.0/clock_line.clock_limit:
                    raise LabscriptError('Commands have been issued to devices attached to %s at t= %s s and %s s. '%(self.name, str(t),str(all_change_times[j+1])) +
                                         'One or more connected devices on ClockLine %s cannot support update delays shorter than %s sec.'%(clock_line.name, str(1.0/clock_line.clock_limit)))
```

from line 826 of labscript.py.  The problem is with the second error check (line 840) that compares the update time of all channels with the clock_line.clock_limit of the current channel.  The resolution that worked for us is to replace this with the maximum clock_limit of all the clock_lines.  It may have been better to replace with self.clock_limit to get the actual limit of the pseudoclock.

Looking through this history, this commit is the one that causes this bug https://github.com/labscript-suite/labscript/commit/56184458fbfdf04e5f3da6c9e19267c4e1d796b4 .  From what I can see I think the issue is that for sequences using the 50/50 duty cycle pulses the change I propose above would change the time of the falling edge of the clock line.

One compromise would be keep the current check for the  50/50 duty cycle pulses and accept my change for the minimum duration pulses, but it seems to me that the better solution is to treat "returning edges" on the same footing as the change times and do an error check for these in this same code block.

The issue specifically is present on line 480 of the PB source code where we see 
```
                if self.pulse_width == 'symmetric':
                    high_time = instruction['step']/2
                else:
                    high_time = self.pulse_width
```
so the PB code is deciding where the returning edges are located just before programming, whereas the more logical time to make this decision would have been during the high-level compilation stage not the low-level stage.

### PR DESCRIPTION
**Pull request by philipstarkey**
Introduce a new attribute for `IntermediateDevice`s that allows them to specify a minimum clock high time in order to allow asymmetric clock ticks when combined with gated clocks on a pseudoclock. `minimum_clock_high_time` defaults to half of the minimum time between `IntermediateDevice` instructions. It be backwards compatible with previous versions of labscript devices.

Fixes #51.
Fixes #85.

I also discovered a bug where the check against the next all change time did not capture the last change time on the clock line because the stop time had not yet been added. This is now fixed.

There were also some issues with various error messages. I've fixed those too and moved to use f strings so they're more readable.

The whole `Pseudoclock.collect_change_times` method has also been reformatted in line with how `black` would format it (since I was working on it anyway). Some commented out code was also removed here too.

It might also solves #53 but I would appreciate @dihm to verify that as it seemed like it might have been slightly different.

I don't have an apparatus to test on so would appreciate wide testing if possible. Should be tested in conjunction with a forthcoming patch to labscript_devices.

### CODE REVIEW

**Comment by dihm** [comment]
It will be a bit before I can actually test this on hardware. In the meantime, I want to make sure I know how to actually build a test that fails under current code but succeeds here. I don't think any of our current experiments are butting into this problem anymore by design so I'll need to craft something from scratch.

Is the basic test to use a PB to clock a Novatech and a DAQ, command a novatech update at time t, the command an update do a DAQ output at time t+tau, with tau varying from say 120us down to 1us? Are there any special edge cases that I should be looking out for? I've looked through the linked issues, but I suspect reproducing any of those specific situations may get rather tricky since most don't actually include scripts or shot files that produce the error.

**Comment by philipstarkey** [comment]
Yep, that's all that you should need to do. Should currently fail when tau is less than 100us, but not with these PRs. There really shouldn't be any bugs, I've only changed error messages and where the stop time is inserted into the change time array. But it's possible there is a bug in how I calculate the default min high time for devices other than the NovaTech or something else like that 🤷 

#53 was your issue report originally so if you don't have something current to reproduce that I think I'd like to just say it was a duplicate of #51 (maybe it was a shutter offset or something that made it seem like it was different).

**Comment by dihm** [comment]
This appears to be working for the standard case. Here is my test script:
```python
  start()
  t = 0

  ao0.constant(t,0)

  dds.setfreq(t, 10*MHz)
  dds.setamp(t, 0.1)
  dds.setphase(t, 0)

  t += start_delay
  pb_2.go_high(t)

  dds.setamp(t, 0.3)

  t += tau

  ao0.constant(t, 0.5)

  t += hold_time
  
  pb_2.go_low(t)

  stop(t+1e-3)
```

I'm checking outputs on a scope, so I'm changing the DDS amplitude as it is easier to see. I then set a constant AnalogOut (on another clockline from the same pulseblaster pseudoclock) to change a time `tau` after the DDS update. With these changes, `tau` can be set as low as 2 us. Anything less throws the error. I'm assuming that is the correct logic for a `minimum_high_time=1e-6` for the novatech (so the code prevents updates for twice the set minimum high time).

I haven't tried to recreate any of the specific scenarios mentioned above. If I can find time I'll try, but I think this can be merged now (assuming logic is right) and fixed later if I find anything in further testing.

**Comment by dihm** [comment]
Forgot to upload the scope trace for the above testing.
scope_0

Red is `pb_2`, blue is the novatech output, and green is the DAQ output. `tau = 2*us`

**Comment by dihm** [comment]
@philipstarkey Browsing old PRs and found this. Are you OK to merge?

**Comment by philipstarkey** [comment]
I think so 🤷

**Comment by dihm** [comment]
Cool. Let's do it!

**Pull request merged**
